name: Probar conexion Runner

on:
  workflow_dispatch:

jobs:
  prueba:
    runs-on: self-hosted

    steps:
      - name: Comprobar Runner
        shell: cmd
        run: |
          echo Runner funcionando correctamente
          echo Equipo: %COMPUTERNAME%
          echo Usuario: %USERNAME%
          echo Fecha:
          echo %DATE% %TIME%
